App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='BlogList'),
    path('write/', views.CreateBlog.as_view(), name='CreateBlog'),
    path('details/<slug:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('signin/', views.login_page, name='signin'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('changeprofileimage/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),

    #Forget password
    #path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    #path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    #path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    #path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index')
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css">

    <title>
        {% block title %}
          Blogs Page
        {% endblock %}
    </title>
  </head>
  <body>
     <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
       <ul class="navbar-nav">

         <li class="nav-item active">
           <a class="nav-link" href="{% url 'index' %}">Home</a>
         </li>

         {% if user.is_authenticated %}

         <li class="nav-item active">
           <a class="nav-link" href="{% url 'App_Blog:CreateBlog' %}">Write Blog</a>
         </li>

         <li class="nav-item active">
           <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
         </li>
         <li class="nav-item active">
           <a class="nav-link" href="{% url 'App_Login:profile' %}">Profile</a>
         </li>
         {% else %}
         <li class="nav-item active">
           <a class="nav-link" href="{% url 'App_Login:signin' %}">Sign Up</a>
         </li>
         <li class="nav-item active">
           <a class="nav-link" href="{% url 'App_Login:signin' %}">Login</a>
         </li>
         {% endif %}
       </ul>
       {% if user.is_authenticated %}
       <div class="nav-item dropdown">
         <a class="nav-link dropdown-toggle"href="#" id="navbardrop" data-toggle='dropdown' text-color='white'>
            {{ user.username }}
         </a>

         <div class="dropdown-menu">
           <a class="dropdown-item"href="{% url 'App_Login:profile' %}">Your Profile</a>
            <a class="dropdown-item"href="{% url 'App_Login:logout' %}">LogOut</a>
         </div>
       </div>
       {% endif %}
     </nav>

     <div class="container" style="padding-top:20px">
       {% block body %}

       {% endblock %}
     </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>